[package]
name = "ralarm-cw"
version = "0.1.0"
edition = "2021"

[dependencies]
ralarm = { path = "../ralarm" }
tokio = { version = "1.39.3", features = ["full"] }
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-cloudwatch = "1.45.0"
